### ISSUE TITLE
这个控件如果放到 Adapter 上是用不 了的 

### ISSUE THREAD

**Issue by DaBaiZhuo** [hust201010701/XDanmuku#14]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                          at java.util.ArrayList.get(ArrayList.java:411)
                                                                          at com.orzangleli.xdanmuku.DanmuContainerView.getBestLine(DanmuContainerView.java:198)
                                                                          at com.orzangleli.xdanmuku.DanmuContainerView.addTypeView(DanmuContainerView.java:150)
                                                                          at com.orzangleli.xdanmuku.DanmuContainerView.addDanmu(DanmuContainerView.java:128)

**Comment by hust201010701** [comment]
麻烦把Adapter代码贴出来，我自己测试没有这个错误。 @lz351003785
